debug:
  enabled: True
  x: 512
  y: 288
client:
  font: 32
  control:
    quit: esc
  color:
    board_detect_threshold: 200
    token_background_threshold: 200
    classes:
      blue:
        b: 163
        g: 128
        r: 110
      green:
        b: 152
        g: 148
        r: 133
      purple:
        b: 150
        g: 138
        r: 137
      red:
        b: 143
        g: 128
        r: 170
resolution:
  camera:
    id: 0
    x: 1920
    y: 1008
  projector:
    x: 1920
    y: 1080