debug:
  enabled: True
  x: 512
  y: 288
client:
  font: 32
  control:
    quit: esc
  color:
    board_detect_threshold: 200
    token_background_threshold: 200
    classes:
      blue:
        b: 163
        g: 128
        r: 110
#      green:
#        b: 152
#        g: 148
#        r: 133
#      purple:
#        b: 150
#        g: 138
#        r: 137
      red:
        b: 143
        g: 128
        r: 170
  detection_smoothing_buffer:
    board: 15
    token: 50
    token_calibration: 5
    board_manual_offset:
      x: 300
      y: 50
  token_update_timeout: 15
resolution:
  camera:
    id: 0
    x: 1920
    y: 1080
    scale_by: 1.5
  projector:
    x: 1920
    y: 1080